"""Protocol for Argos' package/service identity-memory boundary."""

from __future__ import annotations

from typing import Any, Protocol

from argos_src.agent.preference_types import PreferenceSegment
from .models import (
    BiometricEnrollmentResult,
    BiometricSearchResult,
    OwnerResolution,
    PersonMemoryContext,
    PersonProfile,
)


class IdentityMemoryClient(Protocol):
    site_code: str
    retention_class: str

    def close(self) -> None: ...
    def health(self) -> bool: ...
    def resolve_identity(self, *, shared_first_name: str, shared_last_name: str, shared_name: str = "") -> dict[str, Any]: ...
    def get_verified_profile(self, *, username: str, official_name: str) -> dict[str, Any] | None: ...
    def person_profile(self, person_id: str) -> PersonProfile | None: ...
    def person_context(self, person_id: str, *, fallback_profile_lines: tuple[str, ...] = (), fallback_followup_lines: tuple[str, ...] = (), current_text: str | None = None) -> PersonMemoryContext: ...
    def site_blocks(self, site_code: str, *, current_person_id: str | None = None) -> tuple[str, ...]: ...
    def record_encounter(self, *, person_id: str, name: str = "", site_code: str = "", metadata: dict[str, Any] | None = None, observed_at: str | None = None) -> PersonProfile | None: ...
    def search_face(self, *, embedding: Any, model: str, limit: int = 2) -> BiometricSearchResult: ...
    def enroll_face_reference(self, *, person_id: str, embedding: Any, model: str, metadata: dict[str, Any] | None = None, consent_status: str = "consented") -> BiometricEnrollmentResult: ...
    def search_voice(self, *, embedding: Any, model: str, limit: int = 2) -> BiometricSearchResult: ...
    def enroll_voice_reference(self, *, person_id: str, embedding: Any, model: str, metadata: dict[str, Any] | None = None, consent_status: str = "consented") -> BiometricEnrollmentResult: ...
    def has_voice_reference(self, person_id: str) -> bool: ...
    def resolve_turn_owner(self, *, primary_face_candidate: Any = None, visible_face_candidates: tuple[Any, ...] = (), voice_candidate: Any = None, policy_context: dict[str, Any] | None = None) -> OwnerResolution: ...
    def extract_and_store_segment(self, segment: PreferenceSegment, reason: str = "") -> None: ...
    def finish_active_episode(self, *, reason: str = "") -> None: ...
    def search_semantic_memory(self, *, text: str, person_id: str, building_code: str | None = None, limit: int = 5) -> dict[str, list[dict[str, Any]]]: ...
